name: Notify Docker Repository

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'  # Ignore readme changes
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual trigger'
        required: false
        default: 'Manual trigger'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Trigger Docker build
        run: |
          gh api \
           --method POST \
           -H "Accept: application/vnd.github+json" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           /repos/QinCai-rui/rpi-web-shell-docker/actions/workflows/158499551/dispatches \
           -f ref=master
