name: Notify Docker Repository

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'  # Ignore readme changes

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Trigger Workflow in Docker Repository
        run: |
          echo "Changes detected in rpi-web-shell!"
          echo "Build date: $(date)"
          
      - name: Set up environment
        run: |
          echo "REPO_INFO=$(echo ${{ github.repository }} | tr '/' ' ')" >> $GITHUB_ENV
          
      - name: Create trigger artifact
        run: |
          mkdir -p ./trigger
          echo "Repository: ${{ github.repository }}" > ./trigger/info.txt
          echo "Commit: ${{ github.sha }}" >> ./trigger/info.txt
          echo "Triggered at: $(date)" >> ./trigger/info.txt
          
      - name: Upload trigger artifact
        uses: actions/upload-artifact@v4
        with:
          name: trigger-info
          path: ./trigger/
          retention-days: 1
